version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      # Password for root access or - MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: 'mySecret1!'
      MYSQL_DATABASE: 'solid-school-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password1!'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6033:3306'
    # Where our data will be persisted
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

# Names our volume
volumes:
  dbdata: